const fakeDataRecommended = { // getRecommendedPlaylist(10);
  "kind": "youtube#playlistItemListResponse",
  "etag": "UpyphI4vq-iAzX03DMEWyrHTzes",
  "nextPageToken": "CAoQAA",
  "items": [
    {
      "kind": "youtube#playlistItem",
      "etag": "xsA8wwTJ18lUcEsFeVFNC911MrE",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS40MUFDQTIzMTVDRDk4NjQy",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "[MV] IU(아이유) _ eight(에잇) (Prod.&Feat. SUGA of BTS)",
        "description": "[MV] IU(아이유) _ eight(에잇) (Prod.&Feat. SUGA of BTS)\n\n\nK-POP Wonderland, 1theK\n\nK-POP의 모든 즐거움을 1theK(원더케이)에서 만나보세요! :)\nWelcome to the official YouTube channel of K-POP Wonderland, 1theK\n\n\"1theK Originals\" Subscribe 👉 https://www.youtube.com/1theKOriginals?sub_confirmation=1\n\n*****\nHello, this is 1theK. We are working on subtitles now!\nPlease come back and watch it again within a few hours.\nThank you for your waiting and continuing interest :)\n*****\n\n[Notice] 1theK YouTube is also an official channel for the MV, and music shows will count the views from this channel too.\n[공지] 1theK YouTube는 MV를 유통하는 공식 채널로, 1theK에 업로드된 MV 조회수 또한 음악방송 순위에 반영됩니다.\n\n#NEWRELEASE#MV#1theK#원더케이\n\n▶1theK YT : https://www.youtube.com/1theK\n▶1theK FB  : http://www.facebook.com/1theK\n▶1theK TW : https://twitter.com/1theK\n▶1theK Kakao : https://goo.gl/otRpZc\n▶1theK TikTok : https://vt.tiktok.com/2mSMBS",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/TgOu00Mf3kI/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/TgOu00Mf3kI/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/TgOu00Mf3kI/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/TgOu00Mf3kI/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/TgOu00Mf3kI/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 0,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "TgOu00Mf3kI"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "82iduQChpNuPkBOwVY7APIV1uyI",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS5FMDUzMjc0QkNEQkIwOThD",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "eight (Prod. & Feat. SUGA of BTS) (에잇(Prod. & Feat. SUGA of BTS))",
        "description": "Provided to YouTube by Loen Entertainment Inc\n\neight (Prod. & Feat. SUGA of BTS) (에잇(Prod. & Feat. SUGA of BTS)) · IU · SUGA · SUGA\n\neight\n\n℗ 2020 EDAM Entertainment,under license to Kakao M Corp.\n\nReleased on: 2020-05-06\n\nAuthor: 아이유\nAuthor: SUGA\nComposer: SUGA\nComposer: 아이유\nComposer: EL CAPITXN\nArranger: SUGA\nArranger: EL CAPITXN\nArranger: 아이유\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/5_IYVichXbA/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/5_IYVichXbA/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/5_IYVichXbA/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/5_IYVichXbA/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/5_IYVichXbA/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 1,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "5_IYVichXbA"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "qpcy2aYBgsrWMLXojXMMC6P5keg",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS5EMzY2NjcwMkMyRDlDNjFE",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "[슬기로운 의사생활 OST Part 11] 전미도 (JEON MI DO) - 사랑하게 될 줄 알았어 (I Knew I Love) MV",
        "description": "♬ Available on iTunes, Apple Music : https://apple.co/2yyBC3W\n     Listen on Spotify : https://spoti.fi/36q4dVC\n\n\n\n[슬기로운 의사생활 OST Part 11] 전미도 (JEON MI DO) - 사랑하게 될 줄 알았어 (I Knew I Love) MV 입니다.\n\n우선 첫번째 트랙은 가수 우효(OOHYO)의 ‘사노라면’으로, 전인권이 부른 원곡을 리메이크한 곡이다.\n\n‘슬기로운 의사생활’을 통해 재해석된 ‘사노라면’은 따뜻하고 트렌디한 신시사이저와 가창을 맡은 우효의 순수하고 담백한 목소리가 완벽한 조화를 이룬 노래다.\n서정적인 전반부, 밝은 리듬이 가미된 후반부가 인상적이며, ‘사랑의 불시착’, ‘멜로가 체질’, ’화양연화’ 등 많은 드라마 OST 작업에 참여하고 있는 작곡팀 Nodded가\n편곡을 맡았다. 가창을 맡은 우효는 지난 1987년 발매된 전인권의 원곡, 1998년 발매된 김장훈의 리메이크 버전과는 또 다른 자신만의 스타일의 곡을 탄생시켜\n감동을 선사한다. 우효는 삶에 대한 긍정적인 가사를 담담한 목소리로 풀어내며 극중에서 전하고자 하는 메세지를 따뜻하게 전달한다.\n\n이어 OST Part 11 두번째 트랙은 전미도의 ‘사랑하게 될 줄 알았어’로, 전미도가 극중 열연에 이어 OST 가창에도 직접 참여했다는 점에서 주목할 만하다.\n\n지난 2006년 신효범이 발매한 원곡을 새롭게 리메이크한 ‘사랑하게 될 줄 알았어’는 전미도의 진짜 가창력을 보여주는 반전이 살아있는 곡이다. 실제로 전미도는\n지난 2006년 뮤지컬 ‘미스터 마우스’로 데뷔해 ‘닥터 지바고’, ‘스위니 토드’, ‘베르테르’ 등 다수의 뮤지컬 작품에 참여하는 등 뛰어난 가창력을 갖추고 있는 것으로\n알려졌다. 전미도는 이번 OST를 통해 본인의 실력을 유감없이 펼쳐 팬들의 놀라움을 자아낼 것으로 기대된다. ‘아로하’가 음원차트에서 좋은 성적을 보여준만큼,\n전미도의 ‘사랑하게 될 줄 알았어’ 역시 팬들의 큰 반응을 얻을 것으로 예상된다. 또한 ‘사랑하게 될 줄 알았어’는 앞서 OST Part 7 제이레빗의 '넌 언제나'를 편곡한\n싱어송라이터 더오(The O), 밴드 문콕(Moonkock)으로 활동 중인 오동준이 편곡을 맡아 복고적인 신시사이저 사운드와 다채로운 리듬 섹션을 배치하여 현재\n유행하는 뉴트로 컨셉으로 재탄생 시켰다.\n\n\n[Credit]\n\n1.사노라면\n\nLyrics by 김문응\nComposed by 길옥윤\nArranged by Nodded\nSynthesizer Naiv\nGuitar 유지훈\nBass 노지영\nDrum Naiv\n\nMixed by 홍성준 @개나리 싸운드\nMastered by 도정회&박준 @사운드맥스\n\n\n2.사랑하게 될 줄 알았어\n\nLyrics & Composed by 이상규\nArranged by 오동준\nKeyboard 오동준\nGuitar 강건후\nBass 강조성\nChorus 김보라 오동준\n\nRecorded by 강호연 @앤드뮤직 스튜디오\n강조성 @Radiohand Studio\n강건후 @Lighthouse Studio\nMixed by 강조성 @Radiohand Studio\nMastered by 도정회&박준 @사운드맥스\n\n\nOST Producer 마주희 MaOSTro @스튜디오 마음C\nProject Manager 강연희 @스튜디오 마음C",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/rOCymN-Rwiw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/rOCymN-Rwiw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/rOCymN-Rwiw/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/rOCymN-Rwiw/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/rOCymN-Rwiw/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 2,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "rOCymN-Rwiw"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "cj41DhP7Mbb-ZSTVS5V4_a5giFI",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS4yMERBMjFCNTVEOTBGMzA4",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "Agust D '대취타' MV",
        "description": "Agust D '대취타' MV \n\nAgust D - 'D-2' Download\nGoogle:\nhttps://bit.ly/36KbhMM\nhttps://bit.ly/2Ms1H8h\n\nDropbox:\nhttps://bit.ly/2zDUcs5\nhttps://bit.ly/2ZWWhd9\n\n\nCredits:\nDirector: Yong Seok Choi (Lumpens)\nAssistant Director: Jihye Yoon (Lumpens)\n2nd AD: Soeyoung Park, Jongeun Lee\n\nProducer: Emma Sungeun Kim (GE Production)\nProduction manager: Min Sung Kim\nAssistant Producer: Ju Young An\nAssistant Production Manager: Ji Hoon Han\n\nDirector of Photography: Hyunwoo Nam (GDW)\nFocus Puller: Sangwoo Yun\n2nd AC: Eunki Kim\n3rd AC: Kyuwon Seo\nDIT: Yesom Park\n\nGaffer: Kyeong Seok Kim\n1st: Jooil Kim, Myung Hoon Park, Kwon Jang\n2nd: Young Woong Cho, Sungho Kim, Junhee Sung\n3rd: Hanbin Seol, Beong Gwan Lee, Yong Ju Lee, Dae Hyeon Yu\n4th: Yoon Ho So, Chang Hwan Son\n\nJimmy Jib Operator: Youngjung Kim\nJimmy Jib Assistant: Hyun in Kim\n\nGenerator: Jin Chan Heo, Jongho Kim\nCrane: Daesik Seo, Heang Sun Myung\n\nArt Director: Jinsil park, Bona Kim (MuE)\nAssistant Art Team: Yeri Kang, Seonghee Park\nArt team Manager: Ilho Heo\n\nSfx: Just\nSfx Supervisor: Kyoungsoo Park, Changsuk Kim\nSfx Technician: Taehun Kim, Hyun Ahn\n\nStunt Director: Yoon Heon Jung\nStunt Team: Gyeong Seop Noh, Wonjong Song\n\nCostume Designer: Kyeongmi Kim\nCostume Designer Team Leader: Soo Hyun Nam\nCostume Designer Team: Haeun Kim, Siyeon Kim, Nahyun Kim\n\nHead of Department, Extra Hair&Makeup: Sun Park\nKey Extra Makeup Artist: Jooil Kim\nKey Extra Hair Stylist: Hyun Jin Jung\nExtra Hair&Makeup Artist: Doye Park, Cho Eun Kim, Chul Yeon Kim, Ji Seon Yun\n\nSpecial Cast: Taegwan Nam, Jooho Jeong\n\nLocation support: MBC DaeJanggeum Park\nTeam manager: Jong Keun Park\n\nVisual Creative: Nu Kim, Lee Sun Kyoung, Kim Ga Eun, Lee Hye Ri\nPerformance Directing:  Son Sung Deuk, Lee Ga Hun, Lee Byung Eun, Hyewon Park\nArtist Management: Kim Shin Gyu, Ahn jong Hun, Lee Seung Byeong\n\n\nBig Hit Entertainment. Rights are reserved selectively in the video. Unauthorized reproduction is a violation of applicable laws. Manufactured by Big Hit Entertainment, Seoul, Korea.\n\nConnect with BTS: \nhttps://ibighit.com/bts \nhttp://twitter.com/BTS_bighit\nhttp://twitter.com/BTS_twt \nhttp://www.facebook.com/bangtan.official \nhttps://www.youtube.com/user/BANGTANTV \nhttp://instagram.com/BTS.bighitofficial \nhttps://channels.vlive.tv/FE619 \nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.onelink.me/qt3S/94808190\nhttps://www.weibo.com/BTSbighit\nhttps://www.weibo.com/BTSmembers \nhttp://i.youku.com/btsofficial \nhttp://btsblog.ibighit.com  \n\n#AgustD #D_2 #대취타 #Daechwita",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/qGjAWJ2zWWI/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/qGjAWJ2zWWI/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/qGjAWJ2zWWI/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/qGjAWJ2zWWI/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/qGjAWJ2zWWI/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 3,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "qGjAWJ2zWWI"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "D8IMJ-BTe71HwOKpuHk3MKxMwmo",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS4xQjI0RjFFODZEMTlDNzlC",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "TWICE \"MORE & MORE\" M/V",
        "description": "TWICE \"MORE & MORE\" M/V\n\nSpotify https://TWICE.lnk.to/MOREANDMORE/spotify\nApple Music https://TWICE.lnk.to/MOREANDMORE/applemusic\niTunes https://TWICE.lnk.to/MOREANDMORE/itunes \nTWICE Official Shop https://TWICE.lnk.to/Shop \n\nTWICE Official YouTube: http://www.youtube.com/c/TWICE\nTWICE Official Facebook: http://www.facebook.com/JYPETWICE\nTWICE Official Twitter: http://www.twitter.com/JYPETWICE\nTWICE Official Instagram: http://www.instagram.com/TWICETAGRAM\nTWICE Official Homepage: http://TWICE.jype.com\nTWICE Official Fan's: http://fans.jype.com/TWICE\n\nⓒ 2020 JYP Entertainment. All Rights Reserved\n\n#TWICE #트와이스 #MOREandMORE",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/mH0_XpSHkZo/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/mH0_XpSHkZo/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/mH0_XpSHkZo/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/mH0_XpSHkZo/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/mH0_XpSHkZo/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 4,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "mH0_XpSHkZo"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "gBxydj1RkCWYuD22MF-9GQuTw3Y",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS44OEI5NDFFNjg1M0I2RjAw",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "I Knew I Love",
        "description": "Provided to YouTube by Genie Music Corporation\n\nI Knew I Love · JEON MI DO\n\nHOSPITAL PLAYLIST OST Part 11\n\n℗ 2020 스튜디오 마음C, 에그이즈커밍, Stone Music Entertainment\n\nReleased on: 2020-05-22\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/de-y6lX7D6U/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/de-y6lX7D6U/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/de-y6lX7D6U/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/de-y6lX7D6U/sddefault.jpg",
            "width": 640,
            "height": 480
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 5,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "de-y6lX7D6U"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "Aexl-nEqCCRPQiBT_0MLjojUUxU",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS5ERjI4OUYyRDhEODhDNDhC",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "Hug (품)",
        "description": "Provided to YouTube by Loen Entertainment Inc\n\nHug (품) · BOL4\n\nPuberty BookⅡ Pum\n\n℗ 2020 Shofar Music,under license to Kakao M Corp.\n\nReleased on: 2020-05-13\n\nAuthor: 안지영\nComposer: 안지영\nComposer: 바닐라맨\nArranger: 바닐라맨\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/Pkb_GHsA60I/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/Pkb_GHsA60I/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/Pkb_GHsA60I/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/Pkb_GHsA60I/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/Pkb_GHsA60I/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 6,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "Pkb_GHsA60I"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "ZMtxakwhmu85pdortVNYMW3HEiI",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS5EMTQxMzc2Q0Y2NkE4QzM2",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "Happy",
        "description": "Provided to YouTube by SM Entertainment\n\nHappy · TAEYEON\n\nHappy\n\n℗ SM Entertainment\n\nReleased on: 2020-05-04\n\nArtist: TAEYEON\nComposer: Chelcee Grimes\nComposer: Chris Wahle\nArranger: Chris Wahle\nLyricist: Lee Seu Ran\nComposer: Robert Gerongco\nComposer: Samuel Gerongco\n\nAuto-generated by YouTube.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/uVuhV1VVeEI/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/uVuhV1VVeEI/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/uVuhV1VVeEI/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/uVuhV1VVeEI/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/uVuhV1VVeEI/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 7,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "uVuhV1VVeEI"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "1quqA4wC2hdKqn2Gw5jOrwR4K5s",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS5GNjE4MzlGOTUzMzBGMkRG",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "BAEKHYUN 백현 'Candy' MV",
        "description": "BAEKHYUN's 2nd Mini Album \"Delight\" is out now!\nListen and download on your favorite platform: https://smarturl.it/BAEKHYUN_Delight\n\n[Tracklist]\n01 Candy\n02 R U Ridin’?\n03 Bungee\n04 Underwater\n05 Poppin’\n06 Ghost\n07 Love Again\n\nBAEKHYUN Official\nhttp://baekhyun.smtown.com\nhttp://www.youtube.com/baekhyun\nhttp://www.youtube.com/weareoneEXO\nhttp://www.facebook.com/weareoneEXO\nhttp://www.instagram.com/weareone.exo\nhttp://twitter.com/weareoneEXO\n\n#BAEKHYUN #백현 #Candy \nBAEKHYUN 백현 'Candy' MV ℗ SM ENTERTAINMENT",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/gmgcRWxhmqY/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/gmgcRWxhmqY/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/gmgcRWxhmqY/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/gmgcRWxhmqY/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/gmgcRWxhmqY/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 8,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "gmgcRWxhmqY"
        }
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "cc-QOaoGtOf8_PLw_Qd4myM5mRk",
      "id": "UExGZ3F1TG5MNTlhbEdKY2RjMEJFWkpiMnA3SWdrTDBPZS4xQzk3NTVFMUExQjY4RURB",
      "snippet": {
        "publishedAt": "2020-06-08T06:53:37Z",
        "channelId": "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
        "title": "Lady Gaga, Ariana Grande - Rain On Me (Official Music Video)",
        "description": "“CHROMATICA”\nTHE SIXTH ALBUM BY LADY GAGA\nOUT NOW\nhttp://smarturl.it/Chromatica\n\n\"RAIN ON ME”\nTHE NEW SINGLE FROM LADY GAGA WITH ARIANA GRANDE\nOUT NOW\nhttp://smarturl.it/RainOnMeChromatica\n\nDIRECTED BY ROBERT RODRIGUEZ\n\nSHOP THE OFFICIAL CHROMATICA COLLECTION: http://smarturl.it/GagaStore\n\nFOLLOW LADY GAGA:\nFacebook: http://gaga.lk/facebook\nInstagram: http://gaga.lk/Instagram\nSnapchat: http://gaga.lk/Snapchat\nTwitter: http://gaga.lk/Twitter\nWebsite: http://www.ladygaga.com/\nOfficial Store: http://gaga.lk/GagaStore\nEmail List: http://gaga.lk/News\n\nFOLLOW ARIANA GRANDE:\nFacebook: http://ArianaGrande.lnk.to/FacebookYT\nInstagram: http://ArianaGrande.lnk.to/InstagramYT\nTwitter: http://ArianaGrande.lnk.to/TwitterYT\nWebsite: http://ArianaGrande.lnk.to/WebsiteYT\nOfficial Store: http://ArianaGrande.lnk.to/ShopYT\nEmail List: http://ArianaGrande.lnk.to/SignUpYT\n\nMusic video by Lady Gaga, Ariana Grande performing Rain On Me. © 2020 Interscope Records",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/AoAm4om0wTs/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/AoAm4om0wTs/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/AoAm4om0wTs/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/AoAm4om0wTs/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/AoAm4om0wTs/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Music",
        "playlistId": "PLFgquLnL59alGJcdc0BEZJb2p7IgkL0Oe",
        "position": 9,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "AoAm4om0wTs"
        }
      }
    }
  ],
  "pageInfo": {
    "totalResults": 87,
    "resultsPerPage": 10
  }
};

export default fakeDataRecommended;